services:
  - type: web
    name: hunyuan-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api_server:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
